# MCP Server Composer Configuration
# Git and File MCP Servers Example

[composer]
name = "git-file-composer"
conflict_resolution = "prefix"  # Prefix tool names with server name
log_level = "INFO"

# ============================================================================
# Git MCP Server (Proxied via STDIO)
# ============================================================================
[[servers.proxied.stdio]]
name = "git"
command = ["uvx", "mcp-server-git", "--repository", "."]
restart_policy = "never"  # Don't restart - for testing process management
# Optional environment variables for git server
# env = { GIT_AUTHOR_NAME = "MCP Bot", GIT_AUTHOR_EMAIL = "bot@example.com" }

# ============================================================================
# File System MCP Server (Proxied via STDIO)
# ============================================================================
[[servers.proxied.stdio]]
name = "filesystem"
command = ["uvx", "mcp-server-filesystem", "/tmp"]
restart_policy = "never"  # Don't restart - for testing process management
# Optional environment variables for filesystem server
# env = { ALLOWED_OPERATIONS = "read,write,list" }
