global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mcp-composer'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # MCP Server Composer metrics
  - job_name: 'mcp-composer'
    static_configs:
      - targets: ['mcp-composer:8000']
        labels:
          service: 'mcp-composer'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter (if installed)
  - job_name: 'node'
    static_configs:
      - targets: []
        # - node-exporter:9100
        labels:
          service: 'node-exporter'
