# MCP Server Composer Configuration
# Calculator and Echo MCP Servers Example

[composer]
name = "demo-composer"
conflict_resolution = "prefix"  # Prefix tool names with server name
log_level = "INFO"

# ============================================================================
# Calculator MCP Server (Proxied via STDIO)
# ============================================================================
[[servers.proxied.stdio]]
name = "calculator"
command = ["python", "mcp1.py"]
restart_policy = "never"
# Calculator tools: add, subtract, multiply, divide

# ============================================================================
# Echo MCP Server (Proxied via STDIO)
# ============================================================================
[[servers.proxied.stdio]]
name = "echo"
command = ["python", "mcp2.py"]
restart_policy = "never"
# Echo tools: ping, echo, reverse, uppercase, lowercase, count_words
